### ISSUE TITLE
希望可以在@APIs中增加description成员，并可以在页面展示

### ISSUE THREAD

**Issue by paulguard** [3cpj/swagger#1]
cpjit/swagger使用起来挺方便的，我们项目一直在使用，给我们团队的接口展示和沟通带来不少帮助。
现在希望可以在@APIs的成员中增加description，用以表示这个REST服务类的用途，而不是它的路径，路径罗列出来有时候不是非常直观。希望达到如下图效果就更好了。

![image](https://user-images.githubusercontent.com/11598967/29654287-355a24fa-88df-11e7-9f96-8b13af14662b.png)

**Comment by sweetit** [comment]
感谢您的使用！ 我们会尽快做出修改，到时候会邮件通知您的。

**Comment by sweetit** [comment]
@paulguard ，目前是可以实现你要的这种效果的。尝试按照如下方式配置：
1. 在类上面用@APIs标注分类：
![image](https://user-images.githubusercontent.com/9927640/29660358-c40732b0-88f3-11e7-90e8-8537f323faaa.png)
2. 在类对应的package-info.java 文件里面定义分类说明：
![00](https://user-images.githubusercontent.com/9927640/29660762-ad59e96c-88f4-11e7-9e91-6a1d5d545373.png)

以下是运行效果：
![image](https://user-images.githubusercontent.com/9927640/29660845-ea28048c-88f4-11e7-8be2-c0cd867e4d64.png)

**Comment by paulguard** [comment]
谢谢，已经解决
