### ISSUE TITLE
您好，请问可以支持jdk1.6吗？

### ISSUE THREAD

**Issue by iota9star** [3cpj/swagger#5]
如题，如果不行的话，请问如何自行更改？？？万分感谢

**Comment by sweetit** [comment]
jdk6请使用  **分支jdk6**
![1521777110 1](https://user-images.githubusercontent.com/9927640/37810747-ead36330-2e90-11e8-9667-751839790e6d.png)

**Comment by iota9star** [comment]
非常感谢，我试一下
