### ISSUE TITLE
struts是否必须配置为api

### ISSUE THREAD

**Issue by SparkZXP2018** [3cpj/swagger#9]
文档说要配置`<package name="api" namespace="/api" extends="struts-default" >`
但我的项目中已经有/api这个路径了，所以现在配置成了`<package name="apis" namespace="/apis" extends="struts-default" >`

然后通过`http://localhost:8080/项目名/apis/index`能访问到一个不完整的页面，后台看报错信息，提示：`Could not find action or result: /项目名/api/statics?url=lib/jquery-1.8.0.min.js`

从提示看，似乎swagger4j中，写死了api这个路径？怎么才能配置成apis？

**Comment by sweetit** [comment]
@SparkZXP2018 ，你好，必须配置为api

**Comment by sweetit** [comment]
@SparkZXP2018 最新版本（2.2.0）支持自定配置路径。

您可以通过两种方式来使用swagger4j。

与strut2、SpringMVC、Servlet集成
如果您的web项目是基于strut2或SpringMVC或servlet的，您可以在您的web.xml文件中加入如下代码来快速集成swagger4j：
```xml
   <filter>
      <filter-name>swaggerServlet</filter-name>
      <filter-class>com.cpjit.swagger4j.SwaggerFilter</filter-class>
   </filter>
   <filter-mapping>
      <filter-name>swaggerServlet</filter-name>
      <url-pattern>/doc/*</url-pattern>
   </filter-mapping>
```
与spring-boot集成 
如果您的项目是基于spring-boot的，您可以创建一个配置类来快速集成swagger4j：
```java
@Configuration
public class SwaggerConfig {
    @Bean
    public FilterRegistrationBean swaggerFilter() {
        FilterRegistrationBean bean = new FilterRegistrationBean();
        SwaggerFilter filter = new SwaggerFilter();
        bean.setFilter(filter);
        bean.setUrlPatterns(Collections.singletonList("/doc/*"));
        return bean;
    }
}
```
